In [ ]:
# Libraries

import pandas as pd
import json
import numpy as np
import matplotlib.pyplot as plt
import time
import tensorflow as tf
from sklearn.tree import DecisionTreeClassifier
from sklearn.model_selection import train_test_split
from sklearn.metrics import balanced_accuracy_score, recall_score, precision_score, f1_score, roc_auc_score, RocCurveDisplay
from sklearn.model_selection import StratifiedKFold

In [ ]:
# Read data from one of the datasets

df = pd.read_excel(path)
print("Dataset shape: ",df.shape)

,Unnamed: 0,datetime,metadata,_id,ip_api_duration,ip_api_reverse,user_agent,robot,country_code,ip,headers,src,registered_page,request,ip_api_isp,reason,decision
0,0,2024-10-03 15:52:49.023,"{'device': 1, 'is_ip_api_proxy': False, 'is_sa...",66febdd1680e77ba8c06b8b7,540.48,177-191-087-185.xd-dynamic.algarnetsuper.com.br,Mozilla/5.0 (Linux; Android 11; SAMSUNG SM-A02...,NaN,BR,177.191.87.185,"{""X-Ip"":""172.71.2.140"",""Host"":""portal.revistan...",ton,gsp,"{""src"":""ton"",""utm_source"":""Google"",""utm_campai...",algar telecom s/a,"{'isSrcAllowed': True, 'isCrawler': False, 'is...",unsafe
1,1,2024-10-03 14:10:31.986,"{'device': 1, 'is_ip_api_proxy': False, 'is_sa...",66fea5d7696686f470070756,355.01,NaN,Mozilla/5.0 (Linux; Android 10; SAMSUNG SM-A01...,NaN,BR,2804:7c58:9000:cc70:24c8:55fb:4b32:78bd,"{""X-Ip"":""172.70.193.175"",""Host"":""portal.notici...",ton,gsp,"{""src"":""ton"",""utm_source"":""Google"",""utm_campai...",magna batista de souza - me,"{'isSrcAllowed': True, 'isCrawler': False, 'is...",unsafe
2,2,2024-10-02 16:32:50.006,"{'device': 1, 'is_ip_api_proxy': False, 'is_sa...",66fd75b242ccccb23309e2bf,399.05,177-191-124-219.xd-dynamic.algarnetsuper.com.br,Mozilla/5.0 (Linux; Android 11; SAMSUNG SM-A02...,NaN,BR,177.191.124.219,"{""X-Ip"":""172.71.2.140"",""Host"":""portal.revistan...",ton,gsp,"{""src"":""ton"",""utm_source"":""Google"",""utm_campai...",algar telecom s/a,"{'isSrcAllowed': True, 'isCrawler': False, 'is...",unsafe
3,3,2024-10-02 11:04:09.940,"{'device': 1, 'is_ip_api_proxy': False, 'is_sa...",66fd28a9cc6515a0d0037935,313.98,NaN,Mozilla/5.0 (Linux; Android 11; SAMSUNG SM-A02...,NaN,BR,2804:1e68:8006:7708:c122:9218:d78a:dbab,"{""X-Ip"":""172.71.2.140"",""Host"":""portal.revistan...",ton,gsp,"{""src"":""ton"",""utm_source"":""Google"",""utm_campai...",algar telecom s/a,"{'isSrcAllowed': True, 'isCrawler': False, 'is...",unsafe
4,4,2024-10-02 09:48:37.895,"{'device': 1, 'is_ip_api_proxy': False, 'is_sa...",66fd16f5a5592a2f7801b84d,393.89,177-191-081-14.xd-dynamic.algarnetsuper.com.br,Mozilla/5.0 (Linux; Android 11; SAMSUNG SM-A02...,NaN,BR,177.191.81.14,"{""X-Ip"":""172.71.2.133"",""Host"":""portal.revistan...",ton,gsp,"{""src"":""ton"",""utm_source"":""Google"",""utm_campai...",algar telecom s/a,"{'isSrcAllowed': True, 'isCrawler': False, 'is...",unsafe
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
49995,49995,2024-07-06 16:37:19.751,"{'device': 1, 'is_ip_api_proxy': False, 'is_sa...",668972bf2cd14aad8a02a251,673.36,187-85-36-69-wlan.lpnet.com.br,Mozilla/5.0 (Linux; Android 13; SM-A032M Build...,NaN,BR,187.85.36.69,"{""X-Ip"":""172.68.19.22"",""Host"":""portal.noticias...",ton,gsp,"{""src"":""ton"",""utm_source"":""Google"",""utm_campai...",silva & silveira provedor de internet ltda,"{'isSrcAllowed': True, 'isCrawler': False, 'is...",unsafe
49996,49996,2024-07-06 16:37:17.677,"{'device': 1, 'is_ip_api_proxy': False, 'is_sa...",668972bd48f59ebff407555b,535.59,45-181-133-201.cliente.lucfibra.com.br,Mozilla/5.0 (Linux; Android 10; K) AppleWebKit...,NaN,BR,45.181.133.201,"{""X-Ip"":""172.71.238.159"",""Host"":""portal.notici...",ton,gsp,"{""src"":""ton"",""utm_source"":""Google"",""utm_campai...",luc fibra,"{'isSrcAllowed': True, 'isCrawler': False, 'is...",unsafe
49997,49997,2024-07-06 16:37:16.875,"{'device': 1, 'is_ip_api_proxy': False, 'is_sa...",668972bcc2b2f78cc706b5d7,198.92,NaN,Mozilla/5.0 (Linux; Android 10; K) AppleWebKit...,NaN,BR,2804:14d:72a0:81e9:1a65:154a:4905:8e9d,"{""X-Ip"":""162.158.193.227"",""Host"":""portal.notic...",ton,gsp,"{""src"":""ton"",""utm_source"":""Google"",""utm_campai...",claro nxt telecomunicacoes ltda,"{'isSrcAllowed': True, 'isCrawler': False, 'is...",unsafe
49998,49998,2024-07-06 16:37:15.668,"{'device': 1, 'is_ip_api_proxy': False, 'is_sa...",668972bbe1bb8d52fe07c011,769.44,119.55.113.189.dynamic.opcaonet.com.br,Mozilla/5.0 (Linux; Android 10; K) AppleWebKit...,NaN,BR,189.113.55.119,"{""X-Ip"":""172.69.114.20"",""Host"":""portal.noticia...",ton,gsp,"{""src"":""ton"",""utm_source"":""Google"",""utm_campai...",opcao telecom,"{'isSrcAllowed': True, 'isCrawler': False, 'is...",unsafe
49999,49999,2024-07-06 16:37:13.996,"{'device': 1, 'is_ip_api_proxy': False, 'is_sa...",668972b948f59ebff4075551,7.30,128-201-213-61.veloznetaju.com.br,Mozilla/5.0 (Linux; Android 10; K) AppleWebKit...,NaN,BR,128.201.213.61,"{""X-Ip"":""172.70.255.107"",""Host"":""portal.notici...",ton,gsp,"{""src"":""ton"",""utm_source"":""Google"",""utm_campai...",vlz tecnologias eireli,"{'isSrcAllowed': True, 'isCrawler': False, 'is...",unsafe

In [ ]:
# Feature engineering - "headers" column

start_time_headers1 = time.time()
def json_to_dict(json_str):
    try:
        return json.loads(json_str)
    except json.JSONDecodeError:
        return {}

df_dicts = df['headers'].apply(json_to_dict)

df_expanded = pd.json_normalize(df_dicts)
end_time_headers1 = time.time()

# Identify and remove columns with many empty lines
threshold = 0.02*len(df_expanded)
columns_to_drop = [col for col in df_expanded.columns if df_expanded[col].isna().sum() > threshold]
start_time_headers2 = time.time()
df_cleaned = df_expanded.drop(columns=columns_to_drop)

# Concatenate the original Dataframe and the expanded Dataframe from "headers" column
df = pd.concat([df, df_cleaned], axis=1)

# Remove "headers" original column
df.drop(columns=['headers'], inplace=True)
end_time_headers2 = time.time()

,X-Ip,Host,Connection,Cf-Ray,X-Forwarded-For,Cf-Connecting-Ip,Accept-Encoding,Priority,X-Forwarded-Proto,Cdn-Loop,...,Attribution-Reporting-Eligible,Attribution-Reporting-Support,Pragma,X-Miorigin,X-Chrome-Uma-Enabled,Cf-Ew-Via,Cf-Worker,Accept-Charset,X-Wap-Profile,X-Client-Data
0,172.71.2.140,portal.revistanutre.click,close,8cce19f578815213-UDI,177.191.87.185,177.191.87.185,"gzip, br","u=0, i",https,cloudflare; loops=1,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,172.70.193.175,portal.noticiasdiarias.click,close,8ccd84228af927e9-JDO,2804:7c58:9000:cc70:24c8:55fb:4b32:78bd,2804:7c58:9000:cc70:24c8:55fb:4b32:78bd,"gzip, br","u=0, i",https,cloudflare; loops=1,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,172.71.2.140,portal.revistanutre.click,close,8cc617348b30941a-UDI,177.191.124.219,177.191.124.219,"gzip, br","u=0, i",https,cloudflare; loops=1,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,172.71.2.140,portal.revistanutre.click,close,8cc435c298f4941d-UDI,2804:1e68:8006:7708:c122:9218:d78a:dbab,2804:1e68:8006:7708:c122:9218:d78a:dbab,"gzip, br","u=0, i",https,cloudflare; loops=1,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,172.71.2.133,portal.revistanutre.click,close,8cc3c71cdf4f9882-UDI,177.191.81.14,177.191.81.14,"gzip, br","u=0, i",https,cloudflare; loops=1,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
49995,172.68.19.22,portal.noticiasdiarias.click,close,89f104c8fc2b4d29-GRU,187.85.36.69,187.85.36.69,"gzip, br","u=0, i",https,cloudflare,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
49996,172.71.238.159,portal.noticiasdiarias.click,close,89f104bccbe21b34-GRU,45.181.133.201,45.181.133.201,"gzip, br",NaN,https,cloudflare,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
49997,162.158.193.227,portal.noticiasdiarias.click,close,89f104ba1c561189-GIG,2804:14d:72a0:81e9:1a65:154a:4905:8e9d,2804:14d:72a0:81e9:1a65:154a:4905:8e9d,"gzip, br","u=0, i",https,cloudflare,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
49998,172.69.114.20,portal.noticiasdiarias.click,close,89f104aee88ba40b-GRU,189.113.55.119,189.113.55.119,"gzip, br",NaN,https,cloudflare,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
49999,172.70.255.107,portal.noticiasdiarias.click,close,89f104aa18938dcd-MIA,128.201.213.61,128.201.213.61,"gzip, br","u=0, i",https,cloudflare,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [ ]:
# Feature engineering - "request" column
start_time_request1 = time.time()
def json_to_dict(json_str):
    if isinstance(json_str, str):
        try:
            return json.loads(json_str)
        except json.JSONDecodeError:
            return {}
    return {}

df_dicts = df['request'].apply(json_to_dict)
df_dicts.head(len(df_dicts))

df_expanded = pd.json_normalize(df_dicts)
end_time_request1 = time.time()

# Select columns with practical significance
request_columns = ['a', 'b', 'c', 'd', 'e']
start_time_request2 = time.time()
cols_to_keep = request_columns
df_filtered = df_expanded.loc[:, cols_to_keep]
end_time_request2 = time.time()

# Concatenate the original Dataframe and the expanded Dataframe from "request" column
df = pd.concat([df, df_filtered], axis=1)

# Remove "request" original column
df=df.drop(columns=['request'])

,src,utm_source,utm_campaign,utm_medium,utm_content,utm_term,sub2,sub3,sub4,sub5,...,loc,net,pos,dev,gclid,wbraid,gbraid,gad_source,unlock,reengage
0,ton,Google,21281129949,,162863141712,,,,162863141712,700256176065,...,20106,,,m,CjwKCAjwvIWzBhAlEiwAHHWgvdkOWlqx2HNqLnR4UZAhz_...,Cj4KCAjwmYCzBhAbEi4Ayn_0SJu6eCD6S_U7pwoIoOHy54...,0AAAAA9ajGyIPTIkP9tH-Y7bCAv1OdxPp9,1,NaN,NaN
1,ton,Google,21414210901,,,,,,,,...,1031682,x,,m,CjwKCAjwkJm0BhBxEiwAwT1AXDnuciqQd64O3cis-5_4ZR...,,,NaN,NaN,NaN
2,ton,Google,21281129949,,162863141712,,,,162863141712,700256176065,...,20106,,,m,CjwKCAjwvIWzBhAlEiwAHHWgvdkOWlqx2HNqLnR4UZAhz_...,Cj4KCAjwmYCzBhAbEi4Ayn_0SJu6eCD6S_U7pwoIoOHy54...,0AAAAA9ajGyIPTIkP9tH-Y7bCAv1OdxPp9,1,NaN,NaN
3,ton,Google,21281129949,,162863141712,,,,162863141712,700256176065,...,20106,,,m,CjwKCAjwvIWzBhAlEiwAHHWgvdkOWlqx2HNqLnR4UZAhz_...,Cj4KCAjwmYCzBhAbEi4Ayn_0SJu6eCD6S_U7pwoIoOHy54...,0AAAAA9ajGyIPTIkP9tH-Y7bCAv1OdxPp9,1,NaN,NaN
4,ton,Google,21281129949,,162863141712,,,,162863141712,700256176065,...,20106,,,m,CjwKCAjwvIWzBhAlEiwAHHWgvdkOWlqx2HNqLnR4UZAhz_...,Cj4KCAjwmYCzBhAbEi4Ayn_0SJu6eCD6S_U7pwoIoOHy54...,0AAAAA9ajGyIPTIkP9tH-Y7bCAv1OdxPp9,1,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
49949,ton,Google,21414172998,,,,,,,,...,9100751,x,,m,Cj0KCQjw1qO0BhDwARIsANfnkv-vg76QuvbG1gXbJTXfys...,Cj8KCQjws560BhDrARIuAPcE8z2wKI6T2_pOsBEQVtPiCO...,0AAAAA9ajGyLNnwiozlrZgYM9xajZYiLmu,1,NaN,NaN
49950,ton,Google,21414210901,,,,,,,,...,20104,x,,m,Cj0KCQjw1qO0BhDwARIsANfnkv_OMXtB5uPivLpv3Iw9Q9...,,,NaN,ok,NaN
49951,ton,Google,21414210901,,,,,,,,...,9198184,x,,m,Cj0KCQjw1qO0BhDwARIsANfnkv9eQA75xu6KxW_GpI3V_x...,,,NaN,ok,NaN
49952,ton,Google,21414210901,,,,,,,,...,9102154,x,,m,Cj0KCQjw1qO0BhDwARIsANfnkv8H0XeKfQ4lryLXg6eIig...,,,NaN,NaN,NaN
49953,ton,Google,21404630342,,,,,,,,...,9198255,x,,m,Cj0KCQjw1qO0BhDwARIsANfnkv8Vmce6sOERz9ALZLER8A...,,,NaN,ok,NaN

In [ ]:
# Change "OK", "Observation" and "Fraud" for 0, 1 and 2 respectively in "decision" column, which is the target column
# Create a mapping dictionary
decision_map = {'OK': 0, 'Observation': 1, 'Fraud': 2}

# Replace values ​​in the 'decision' column using the map method
df['decision'] = df['decision'].map(decision_map)

In [ ]:
# Treatment time of the request columns and headers per sample
time_headers_request = (end_time_headers1 - start_time_headers1 + end_time_headers2 - start_time_headers2 + end_time_request1 - start_time_request1 + end_time_request2 - start_time_request2) / len(df)

0.00010832238674163818

In [ ]:
# Separate Dataframe into input data (features) and output data (labels)
X = df.drop(columns=['decision'])
y = df['decision']

In [ ]:
# Display the absolute count and percentage of each class
class_distribution = df['decision'].value_counts()
class_percentage = df['decision'].value_counts(normalize=True) * 100

class_distribution_results = pd.DataFrame({
    'Count': class_distribution,
    'Percentage (%)': pclass_percentage
})

print(class_distribution_results)

          Contagem  Porcentagem (%)
decision
0            49813           99.626
1              138            0.276
2               49            0.098

In [ ]:
# Stratified K-Fold

# Instantiate StratifiedKFold
skf = StratifiedKFold(n_splits=10)

# To store the results of each fold
accuracies = []
balanced_accuracies = []
recalls = []
total_time = []
precisions = []
f1_scores = []
roc_aucs_by_class = []
micro_precisions = []
micro_recalls = []
micro_f1_scores = []
micro_roc_aucs = []

# Loop over splits
for i, (train_index, test_index) in enumerate(skf.split(X, y)):
    X_train, X_test = X.iloc[train_index], X.iloc[test_index]
    y_train, y_test = y.iloc[train_index], y.iloc[test_index]
    processing_time = []

    # Natural Language Processing in each train column
    for col in X_train.columns:
        # Get unique column values
        unique_values = X_train[col].unique()

        # Check if all values ​​are empty or NaN
        if len(unique_values) == 1 and (unique_values[0] == '' or pd.isna(unique_values[0])):
            print(f"Column '{col}' was ignored due to empty values ​​or NaN.")
            X_train=X_train.drop(columns=[col])
            X_test=X_test.drop(columns=[col])
            continue  # Ignore this column and move to the next
        elif len(unique_values) == 2 and (unique_values[0] == '' or pd.isna(unique_values[0])) and (unique_values[1] == '' or pd.isna(unique_values[1])):
            print(f"Column '{col}' was ignored due to empty values ​​or NaN.")
            X_train=X_train.drop(columns=[col])
            X_test=X_test.drop(columns=[col])
            continue  # Ignore this column and move to the next

        # Initial column treatment
        X_train.loc[:, col] = X_train[col].fillna('').astype(str).str.replace(r'[^\w\s]', ' ', regex=True)
        start_time0 = time.time()
        X_test.loc[:, col] = X_test[col].fillna('').astype(str).str.replace(r'[^\w\s]', ' ', regex=True)
        end_time0 = time.time()

        # Instatiate TextVectorization
        vectorizer = tf.keras.layers.TextVectorization(output_mode='int', standardize=None, output_sequence_length=30)
        vectorizer.adapt(X_train[col].values)  # Vector adjustment to training vocabulary

        # Convert text into tokens sequences with automatic padding
        train_padded = vectorizer(X_train[col].values)
        start_time1 = time.time()
        test_padded = vectorizer(X_test[col].values)
        end_time1 = time.time()

        # Convert to dataframe and replace the original columns
        X_train_col = pd.DataFrame(train_padded.numpy(), index=X_train.index)
        X_train = X_train.drop(columns=[col])
        X_train = pd.concat([X_train, X_train_col], axis=1)

        start_time2 = time.time()
        X_test_col = pd.DataFrame(test_padded.numpy(), index=X_test.index)
        X_test = X_test.drop(columns=[col])
        X_test = pd.concat([X_test, X_test_col], axis=1)
        end_time2 = time.time()
        processing_time.append((end_time0 - start_time0) + (end_time1 - start_time1) + (end_time2 - start_time2))

    # Decision Tree
    X_train.columns = X_train.columns.astype(str)
    start_time3 = time.time()
    X_test.columns = X_test.columns.astype(str)
    end_time3 = time.time()

    model = DecisionTreeClassifier()
    model.fit(X_train, y_train) # training

    # Predict method on the test set
    start_time4 = time.time()
    y_pred = model.predict(X_test)
    end_time4 = time.time()

    # Balanced Accuracy
    balanced_accuracy = balanced_accuracy_score(y_test, y_pred)
    balanced_accuracies.append(balanced_accuracy)

    # Recall
    recall = recall_score(y_test, y_pred, average=None)
    recalls.append(recall)

    micro_recall = recall_score(y_test, y_pred, average='micro')
    micro_recalls.append(micro_recall)

    # Precision
    precision = precision_score(y_test, y_pred, average=None)
    precisions.append(precision)

    micro_precision = precision_score(y_test, y_pred, average='micro')
    micro_precisions.append(micro_precision)

    # F1-Score

    f1 = f1_score(y_test, y_pred, average=None)
    f1_scores.append(f1)

    micro_f1 = f1_score(y_test, y_pred, average='micro')
    micro_f1_scores.append(micro_f1)

    # Calculate ROC-AUC for each class separately
    roc_auc_classes = []
    y_proba = model.predict_proba(X_test)
    for class_idx in range(len(model.classes_)):
        y_true_binary = (y_test == class_idx).astype(int)
        auc = roc_auc_score(y_true_binary, y_proba[:, class_idx])
        roc_auc_classes.append(auc)
    roc_aucs_by_class.append(roc_auc_classes)

    micro_roc_auc = roc_auc_score(y_test, model.predict_proba(X_test), multi_class="ovr", average="micro")
    micro_roc_aucs.append(micro_roc_auc)

    total_time.append(sum(tempo_processamento) + end_time3-start_time3 + end_time4-start_time4)


# Calculate average and standard deviation for each metric between 10 folds
mean_balanced_accuracy = np.mean(balanced_accuracies)
std_balanced_accuracy = np.std(balanced_accuracies)

mean_recall = np.mean(recalls, axis=0)
std_recall = np.std(recalls, axis=0)

mean_micro_recall = np.mean(micro_recalls)
std_micro_recall = np.std(micro_recalls)

mean_precision = np.mean(precisions, axis=0)
std_precision = np.std(precisions, axis=0)

mean_micro_precision = np.mean(micro_precisions)
std_micro_precision = np.std(micro_precisions)

mean_f1 = np.mean(f1_scores, axis=0)
std_f1 = np.std(f1_scores, axis=0)

mean_micro_f1 = np.mean(micro_f1_scores)
std_micro_f1 = np.std(micro_f1_scores)

roc_aucs_by_class = np.array(roc_aucs_by_class)
mean_roc_auc_by_class = np.mean(roc_aucs_by_class, axis=0)
std_roc_auc_by_class = np.std(roc_aucs_by_class, axis=0)

mean_micro_roc_auc = np.mean(micro_roc_aucs)
std_micro_roc_auc = np.std(micro_roc_aucs)

time_per_sample = (np.mean(total_time) / len(X_test))*1000 + tempo*1000

print(f"Average Sample Processing Time: {time_per_sample:.4f} ms")
print()

print(f"Balanced accuracy average: {mean_balanced_accuracy}")
print(f"Standard deviation of balanced accuracy: {std_balanced_accuracy}")
print()

print(f"Average recall for each class: {mean_recall}")
print(f"Standard deviation of recall for each class: {std_recall}")
print()

print(f"Average micro-recall: {mean_micro_recall}")
print(f"Standard deviation of micro-recall: {std_micro_recall}")
print()

print(f"Average precision for each class: {mean_precision}")
print(f"Standard deviation of precision for each class: {std_precision}")
print()

print(f"Average micro-precision: {mean_micro_precision}")
print(f"Standard deviation of micro-precision: {std_micro_precision}")
print()

print(f"Average F1-Score for each class: {mean_f1}")
print(f"Standard deviation of F1-Score for eacho class: {std_f1}")
print()

print(f"Average micro-F1-Score: {mean_micro_f1}")
print(f"Standard deviation of micro-F1-Score: {std_micro_f1}")
print()

for class_idx, (mean_auc, std_auc) in enumerate(zip(mean_roc_auc_by_class, std_roc_auc_by_class)):
    print(f"Class {class_idx}: Average ROC-AUC = {mean_auc:.4f}, standard deviation of ROC_AUC = {std_auc:.4f}")

print(f"Average micro-ROC-AUC: {mean_micro_roc_auc}")
print(f"Standard deviation of micro-ROC-AUC: {std_micro_roc_auc}")
print()

ip_api_reverse
user_agent
country_code
ip
ip_api_isp
reason
Cf-Ray
X-Forwarded-For
Accept-Encoding
X-Forwarded-Proto
Accept-Language
Sec-Fetch-Dest
Sec-Fetch-Mode
Sec-Fetch-Site
Accept
Upgrade-Insecure-Requests
Referer
cwr
twr
A coluna 'twr' foi ignorada devido a valores vazios ou NaN.
gwr
domain
cr
plc
A coluna 'plc' foi ignorada devido a valores vazios ou NaN.
mtx
rdn
kw
A coluna 'kw' foi ignorada devido a valores vazios ou NaN.
cpc
disp
A coluna 'disp' foi ignorada devido a valores vazios ou NaN.
int
loc
net
pos
A coluna 'pos' foi ignorada devido a valores vazios ou NaN.
dev
gclid
wbraid
gbraid
ref_id
(45000, 960)
ip_api_reverse
user_agent
country_code
ip
ip_api_isp
reason
Cf-Ray
X-Forwarded-For
Accept-Encoding
X-Forwarded-Proto
Accept-Language
Sec-Fetch-Dest
Sec-Fetch-Mode
Sec-Fetch-Site
Accept
Upgrade-Insecure-Requests
Referer
cwr
twr
A coluna 'twr' foi ignorada devido a valores vazios ou NaN.
gwr
domain
cr
plc
A coluna 'plc' foi ignorada devido a valores vazios ou NaN.
mtx
rdn
kw
A coluna 'kw' foi ignorada devido a valores vazios ou NaN.
cpc
disp
A coluna 'disp' foi ignorada devido a valores vazios ou NaN.
int
loc
net
pos
A coluna 'pos' foi ignorada devido a valores vazios ou NaN.
dev
gclid
wbraid
gbraid
ref_id
(45000, 960)
ip_api_reverse
user_agent
country_code
ip
ip_api_isp
reason
Cf-Ray
X-Forwarded-For
Accept-Encoding
X-Forwarded-Proto
Accept-Language
Sec-Fetch-Dest
Sec-Fetch-Mode
Sec-Fetch-Site
Accept
Upgrade-Insecure-Requests
Referer
cwr
twr
A coluna 'twr' foi ignorada devido a valores vazios ou NaN.
gwr
domain
cr
plc
A coluna 'plc' foi ignorada devido a valores vazios ou NaN.
mtx
rdn
kw
A coluna 'kw' foi ignorada devido a valores vazios ou NaN.
cpc
disp
A coluna 'disp' foi ignorada devido a valores vazios ou NaN.
int
loc
net
pos
A coluna 'pos' foi ignorada devido a valores vazios ou NaN.
dev
gclid
wbraid
gbraid
ref_id
(45000, 960)
ip_api_reverse
user_agent
country_code
ip
ip_api_isp
reason
Cf-Ray
X-Forwarded-For
Accept-Encoding
X-Forwarded-Proto
Accept-Language
Sec-Fetch-Dest
Sec-Fetch-Mode
Sec-Fetch-Site
Accept
Upgrade-Insecure-Requests
Referer
cwr
twr
A coluna 'twr' foi ignorada devido a valores vazios ou NaN.
gwr
domain
cr
plc
A coluna 'plc' foi ignorada devido a valores vazios ou NaN.
mtx
rdn
kw
A coluna 'kw' foi ignorada devido a valores vazios ou NaN.
cpc
disp
A coluna 'disp' foi ignorada devido a valores vazios ou NaN.
int
loc
net
pos
A coluna 'pos' foi ignorada devido a valores vazios ou NaN.
dev
gclid
wbraid
gbraid
ref_id
(45000, 960)

/usr/local/lib/python3.10/dist-packages/sklearn/metrics/_classification.py:1565: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))

ip_api_reverse
user_agent
country_code
ip
ip_api_isp
reason
Cf-Ray
X-Forwarded-For
Accept-Encoding
X-Forwarded-Proto
Accept-Language
Sec-Fetch-Dest
Sec-Fetch-Mode
Sec-Fetch-Site
Accept
Upgrade-Insecure-Requests
Referer
cwr
twr
A coluna 'twr' foi ignorada devido a valores vazios ou NaN.
gwr
domain
cr
plc
A coluna 'plc' foi ignorada devido a valores vazios ou NaN.
mtx
rdn
kw
A coluna 'kw' foi ignorada devido a valores vazios ou NaN.
cpc
disp
A coluna 'disp' foi ignorada devido a valores vazios ou NaN.
int
loc
net
pos
A coluna 'pos' foi ignorada devido a valores vazios ou NaN.
dev
gclid
wbraid
gbraid
ref_id
(45000, 960)
ip_api_reverse
user_agent
country_code
ip
ip_api_isp
reason
Cf-Ray
X-Forwarded-For
Accept-Encoding
X-Forwarded-Proto
Accept-Language
Sec-Fetch-Dest
Sec-Fetch-Mode
Sec-Fetch-Site
Accept
Upgrade-Insecure-Requests
Referer
cwr
twr
A coluna 'twr' foi ignorada devido a valores vazios ou NaN.
gwr
domain
cr
plc
A coluna 'plc' foi ignorada devido a valores vazios ou NaN.
mtx
rdn
kw
A coluna 'kw' foi ignorada devido a valores vazios ou NaN.
cpc
disp
A coluna 'disp' foi ignorada devido a valores vazios ou NaN.
int
loc
net
pos
A coluna 'pos' foi ignorada devido a valores vazios ou NaN.
dev
gclid
wbraid
gbraid
ref_id
(45000, 960)
ip_api_reverse
user_agent
country_code
ip
ip_api_isp
reason
Cf-Ray
X-Forwarded-For
Accept-Encoding
X-Forwarded-Proto
Accept-Language
Sec-Fetch-Dest
Sec-Fetch-Mode
Sec-Fetch-Site
Accept
Upgrade-Insecure-Requests
Referer
cwr
twr
A coluna 'twr' foi ignorada devido a valores vazios ou NaN.
gwr
domain
cr
plc
A coluna 'plc' foi ignorada devido a valores vazios ou NaN.
mtx
rdn
kw
A coluna 'kw' foi ignorada devido a valores vazios ou NaN.
cpc
disp
A coluna 'disp' foi ignorada devido a valores vazios ou NaN.
int
loc
net
pos
A coluna 'pos' foi ignorada devido a valores vazios ou NaN.
dev
gclid
wbraid
gbraid
ref_id
(45000, 960)
ip_api_reverse
user_agent
country_code
ip
ip_api_isp
reason
Cf-Ray
X-Forwarded-For
Accept-Encoding
X-Forwarded-Proto
Accept-Language
Sec-Fetch-Dest
Sec-Fetch-Mode
Sec-Fetch-Site
Accept
Upgrade-Insecure-Requests
Referer
cwr
twr
A coluna 'twr' foi ignorada devido a valores vazios ou NaN.
gwr
domain
cr
plc
A coluna 'plc' foi ignorada devido a valores vazios ou NaN.
mtx
rdn
kw
A coluna 'kw' foi ignorada devido a valores vazios ou NaN.
cpc
disp
A coluna 'disp' foi ignorada devido a valores vazios ou NaN.
int
loc
net
pos
A coluna 'pos' foi ignorada devido a valores vazios ou NaN.
dev
gclid
wbraid
gbraid
ref_id
(45000, 960)
ip_api_reverse
user_agent
country_code
ip
ip_api_isp
reason
Cf-Ray
X-Forwarded-For
Accept-Encoding
X-Forwarded-Proto
Accept-Language
Sec-Fetch-Dest
Sec-Fetch-Mode
Sec-Fetch-Site
Accept
Upgrade-Insecure-Requests
Referer
cwr
twr
A coluna 'twr' foi ignorada devido a valores vazios ou NaN.
gwr
domain
cr
plc
A coluna 'plc' foi ignorada devido a valores vazios ou NaN.
mtx
rdn
kw
A coluna 'kw' foi ignorada devido a valores vazios ou NaN.
cpc
disp
A coluna 'disp' foi ignorada devido a valores vazios ou NaN.
int
loc
net
pos
A coluna 'pos' foi ignorada devido a valores vazios ou NaN.
dev
gclid
wbraid
gbraid
ref_id
(45000, 960)
ip_api_reverse
user_agent
country_code
ip
ip_api_isp
reason
Cf-Ray
X-Forwarded-For
Accept-Encoding
X-Forwarded-Proto
Accept-Language
Sec-Fetch-Dest
Sec-Fetch-Mode
Sec-Fetch-Site
Accept
Upgrade-Insecure-Requests
Referer
cwr
twr
A coluna 'twr' foi ignorada devido a valores vazios ou NaN.
gwr
domain
cr
plc
A coluna 'plc' foi ignorada devido a valores vazios ou NaN.
mtx
rdn
kw
A coluna 'kw' foi ignorada devido a valores vazios ou NaN.
cpc
disp
A coluna 'disp' foi ignorada devido a valores vazios ou NaN.
int
loc
net
pos
A coluna 'pos' foi ignorada devido a valores vazios ou NaN.
dev
gclid
wbraid
gbraid
ref_id
(45000, 960)
9

Tempo médio de processamento por amostra: 0.5245 ms

Média da acurácia balanceada: 0.9017082275283439
Desvio padrão da acurácia balanceada: 0.12643522343643032

Média do recall para cada classe: [0.99995985 0.98516484 0.72      ]
Desvio padrão do recall para cada classe: [8.03051596e-05 2.96957563e-02 3.81575681e-01]

Média do micro-recall: 0.9996400000000001
Desvio padrão do micro-recall: 0.00036660605559647285

Média da precisão para cada classe: [0.99991974 0.93486842 0.76666667]
Desvio padrão da precisão para cada classe: [1.83896755e-04 1.05691972e-01 3.88730126e-01]

Média do micro-precision: 0.9996400000000001
Desvio padrão do micro-precision: 0.00036660605559647285

Média do F1-Score para cada classe: [0.99993978 0.9553266  0.73459596]
Desvio padrão do F1-Score para cada classe: [9.19778189e-05 5.77691454e-02 3.74075826e-01]

Média do micro-F1-Score: 0.9996400000000001
Desvio padrão do micro-F1-Score: 0.00036660605559647285

Classe 0: Média do ROC-AUC = 0.9895, Desvio padrão = 0.0241
Classe 1: Média do ROC-AUC = 0.9925, Desvio padrão = 0.0148
Classe 2: Média do ROC-AUC = 0.8600, Desvio padrão = 0.1908
Média do micro-ROC-AUC: 0.9997300000000001
Desvio padrão do micro-ROC-AUC: 0.0002749545416972959

/usr/local/lib/python3.10/dist-packages/sklearn/metrics/_classification.py:1565: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))

In [ ]:
# Grid search loop for decision tree classifier with Stratified K-Fold

# Hyperparameter lists
criterion_list =  ['gini', 'entropy', 'log_loss']
splitter_list = ['best', 'random']
max_features_list = ['sqrt', 'log2', None]
ccp_alpha_list = [0.1, .01, .001]
class_weight_list = ['balanced', None]
min_samples_split_list = [0.01, 0.1, 0.15]
min_samples_leaf_list = [0.01, 0.1, 0.15]
min_impurity_decrease_list = [0.0, 0.01, 0.05, 0.1, 0.15]
min_weight_fraction_leaf_list = [0.01, 0.05, 0.1, 0.15]

# Instantiate StratifiedKFold
skf = StratifiedKFold(n_splits=5)

# Loop over splits
for i, (train_index, test_index) in enumerate(skf.split(X, y)):
    X_train, X_test = X.iloc[train_index], X.iloc[test_index]
    y_train, y_test = y.iloc[train_index], y.iloc[test_index]

    # Natural Language Processing in each train column
    for col in X_train.columns:
        # Get unique column values
        unique_values = X_train[col].unique()

        # Check if all values ​​are empty or NaN
        if len(unique_values) == 1 and (unique_values[0] == '' or pd.isna(unique_values[0])):
            print(f"Column '{col}' was ignored due to empty values ​​or NaN.")
            X_train=X_train.drop(columns=[col])
            X_test=X_test.drop(columns=[col])
            continue  # Ignore this column and move to the next
        elif len(unique_values) == 2 and (unique_values[0] == '' or pd.isna(unique_values[0])) and (unique_values[1] == '' or pd.isna(unique_values[1])):
            print(f"Column '{col}' was ignored due to empty values ​​or NaN.")
            X_train=X_train.drop(columns=[col])
            X_test=X_test.drop(columns=[col])
            continue  # Ignore this column and move to the next

        # Initial column treatment
        X_train.loc[:, col] = X_train[col].fillna('').astype(str).str.replace(r'[^\w\s]', ' ', regex=True)
        X_test.loc[:, col] = X_test[col].fillna('').astype(str).str.replace(r'[^\w\s]', ' ', regex=True)

        # Instatiate TextVectorization
        vectorizer = tf.keras.layers.TextVectorization(output_mode='int', standardize=None, output_sequence_length=30)
        vectorizer.adapt(X_train[col].values)  # Vector adjustment to training vocabulary

        # Convert text into tokens sequences with automatic padding
        train_padded = vectorizer(X_train[col].values)
        test_padded = vectorizer(X_test[col].values)

        # Convert to dataframe and replace the original columns
        X_train_col = pd.DataFrame(train_padded.numpy(), index=X_train.index)
        X_train = X_train.drop(columns=[col])
        X_train = pd.concat([X_train, X_train_col], axis=1)

        X_test_col = pd.DataFrame(test_padded.numpy(), index=X_test.index)
        X_test = X_test.drop(columns=[col])
        X_test = pd.concat([X_test, X_test_col], axis=1)

    # Decision Tree
    X_train.columns = X_train.columns.astype(str)
    X_test.columns = X_test.columns.astype(str)

    for criterion in criterion_list:
      for splitter in splitter_list:
          for max_features in max_features_list:
              for ccp_alpha in ccp_alpha_list:
                  for class_weight in class_weight_list:
                      for min_samples_split in min_samples_split_list:
                          for min_samples_leaf in min_samples_leaf_list:
                              for min_impurity_decrease in min_impurity_decrease_list:
                                  for min_weight_fraction_leaf in min_weight_fraction_leaf_list:
                                      model = DecisionTreeClassifier(criterion=criterion, splitter=splitter, max_features=max_features, ccp_alpha=ccp_alpha, max_depth=None,
                                                              max_leaf_nodes=None, class_weight=class_weight, min_samples_split=min_samples_split, min_samples_leaf=min_samples_leaf,
                                                              min_impurity_decrease=min_impurity_decrease, min_weight_fraction_leaf=min_weight_fraction_leaf)

                                      history = model.fit(X_train, y_train)

                                      # make predictions
                                      y_predicted = model.predict(X_test)

                                      # evaluate predictions
                                      # balanced accuracy
                                      balanced_accuracy = balanced_accuracy_score(y_test, y_predicted)

                                      # recall
                                      recall = recall_score(y_test, y_predicted, average=None)

                                      results_dict = {
                                          "fold" : i,
                                          "criterion": criterion,
                                          "splitter": splitter,
                                          "max_features": max_features,
                                          "ccp_alpha": ccp_alpha,
                                          "class_weight": class_weight,
                                          "min_samples_split": min_samples_split,
                                          "min_samples_leaf": min_samples_leaf,
                                          "min_impurity_decrease": min_impurity_decrease,
                                          "min_weight_fraction_leaf": min_weight_fraction_leaf,
                                          "balanced accuracy": balanced_accuracy,
                                          "recalls": recall
                                      }
                                      results.append(results_dict)

df = pd.DataFrame(results)

# Treat the results (recall and balanced accuracy) and make a new dataframe with the averages and standard deviation between the folds
num = int(df.shape[0]/5)

bal_acc = []
avgs_bal_acc = []
stds_bal_acc = []

recalls = []
avgs_recalls = []
stds_recalls = []

for n in range(0,num):
  bal_acc1 = [df["balanced accuracy"][n], df["balanced accuracy"][n+num],df["balanced accuracy"][n+(2*num)], df["balanced accuracy"][n+(3*num)], df["balanced accuracy"][n+(4*num)]]
  recall1 = [df["recalls"][n], df["recalls"][n+num],df["recalls"][n+(2*num)], df["recalls"][n+(3*num)], df["recalls"][n+(4*num)]]
  bal_acc.append(bal_acc1)
  avgs_bal_acc.append(np.mean(bal_acc[n]))
  stds_bal_acc.append(np.std(bal_acc[n]))

  recalls.append(recall1)
  avgs_recalls.append(np.mean(recalls[n], axis=0))
  stds_recalls.append(np.std(recalls[n], axis=0))


avg_std = {
    "Bal. acc.": avgs_bal_acc,
    "Bal. acc. (std)": stds_bal_acc,
}

num_classes = len(avgs_recalls[0])
for i in range(num_classes):
    avg_std[f"Recall Class {i+1}"] = [recall[i] for recall in avgs_recalls]
    avg_std[f"Recall (std) Class {i+1}"] = [std[i] for std in stds_recalls]

df_avg_std = pd.DataFrame(avg_std)

df_end = df.drop(columns=["fold", "balanced accuracy", "recalls"])
df_end = df_end.drop(range(num, num*5))
df_end = pd.concat([df_end, df_avg_std], axis=1)

# Sorting df_end according to the balanced accuracy (the biggest in the first line)
df_end = df_end.sort_values("Bal. acc.", ascending=False)

# The first line will show the best hyperparameters